export const banks = [
  { code: '00007', name: 'Banco De Galicia Y Buenos Aires S.A.U.' },
  { code: '00011', name: 'Banco De La Nacion Argentina' },
  { code: '00014', name: 'Banco De La Provincia De Buenos Aires' },
  { code: '00015', name: 'Industrial And Commercial Bank Of China' },
  { code: '00016', name: 'Citibank N.A.' },
  { code: '00017', name: 'Banco BBVA Argentina S.A.' },
  { code: '00020', name: 'Banco De La Provincia De Cordoba S.A.' },
  { code: '00027', name: 'Banco Supervielle S.A.' },
  { code: '00029', name: 'Banco De La Ciudad De Buenos Aires' },
  { code: '00034', name: 'Banco Patagonia S.A.' },
  { code: '00044', name: 'Banco Hipotecario S.A.' },
  { code: '00045', name: 'Banco De San Juan S.A.' },
  { code: '00065', name: 'Banco Municipal De Rosario' },
  { code: '00072', name: 'Banco Santander Argentina S.A.' },
  { code: '00083', name: 'Banco Del Chubut S.A.' },
  { code: '00086', name: 'Banco De Santa Cruz S.A.' },
  { code: '00093', name: 'Banco De La Pampa Sociedad De Economía M' },
  { code: '00094', name: 'Banco De Corrientes S.A.' },
  { code: '00097', name: 'Banco Provincia Del Neuquén Sociedad Anó' },
  { code: '00131', name: 'Bank Of China Limited Sucursal Buenos Ai' },
  { code: '00143', name: 'Brubank S.A.U.' },
  { code: '00147', name: 'Banco Interfinanzas S.A.' },
  { code: '00150', name: 'Hsbc Bank Argentina S.A.' },
  { code: '00158', name: 'Open Bank Argentina S.A.' },
  { code: '00165', name: 'Jpmorgan Chase Bank, National Associatio' },
  { code: '00191', name: 'Banco Credicoop Cooperativo Limitado' },
  { code: '00198', name: 'Banco De Valores S.A.' },
  { code: '00247', name: 'Banco Roela S.A.' },
  { code: '00254', name: 'Banco Mariva S.A.' },
  { code: '00259', name: 'Banco Itau Argentina S.A.' },
  { code: '00266', name: 'Bnp Paribas' },
  { code: '00268', name: 'Banco Provincia De Tierra Del Fuego' },
  { code: '00269', name: 'Banco De La Republica Oriental Del Urugu' },
  { code: '00277', name: 'Banco Saenz S.A.' },
  { code: '00281', name: 'Banco Meridian S.A.' },
  { code: '00285', name: 'Banco Macro S.A.' },
  { code: '00299', name: 'Banco Comafi Sociedad Anonima' },
  { code: '00300', name: 'Banco De Inversion Y Comercio Exterior S' },
  { code: '00301', name: 'Banco Piano S.A.' },
  { code: '00305', name: 'Banco Julio Sociedad Anonima' },
  { code: '00309', name: 'Banco Rioja Sociedad Anonima Unipersonal' },
  { code: '00310', name: 'Banco Del Sol S.A.' },
  { code: '00311', name: 'Nuevo Banco Del Chaco S. A.' },
  { code: '00312', name: 'Banco Voii S.A.' },
  { code: '00315', name: 'Banco De Formosa S.A.' },
  { code: '00319', name: 'Banco CMF S.A.' },
  { code: '00321', name: 'Banco De Santiago Del Estero S.A.' },
  { code: '00322', name: 'Banco Industrial S.A.' },
  { code: '00330', name: 'Nuevo Banco De Santa Fe Sociedad Anonima' },
  { code: '00331', name: 'Banco Cetelem Argentina S.A.' },
  { code: '00332', name: 'Banco De Servicios Financieros S.A.' },
  { code: '00338', name: 'Banco De Servicios Y Transacciones S.A.' },
  { code: '00339', name: 'Rci Banque S.A.' },
  { code: '00340', name: 'Bacs Banco De Credito Y Securitizacion S' },
  { code: '00341', name: 'Banco Masventas S.A.' },
  { code: '00384', name: 'Wilobank S.A.U.' },
  { code: '00386', name: 'Nuevo Banco De Entre Ríos S.A.' },
  { code: '00389', name: 'Banco Columbia S.A.' },
  { code: '00426', name: 'Banco Bica S.A.' },
  { code: '00431', name: 'Banco Coinag S.A.' },
  { code: '00432', name: 'Banco De Comercio S.A.' },
  { code: '00435', name: 'Banco Sucredito Regional S.A.U.' },
  { code: '00448', name: 'Banco Dino S.A.' },
  { code: '44077', name: 'Compañia Financiera Argentina S.A.' },
  { code: '44088', name: 'Volkswagen Financial Services Compañia F' },
  { code: '44090', name: 'Iudu Compañía Financiera S.A.' },
  { code: '44092', name: 'Fca Compañia Financiera S.A.' },
  { code: '44093', name: 'Gpat Compañia Financiera S.A.U.' },
  { code: '44094', name: 'Mercedes-Benz Compañía Financiera Argent' },
  { code: '44095', name: 'Rombo Compañía Financiera S.A.' },
  { code: '44096', name: 'John Deere Credit Compañía Financiera S.' },
  { code: '44098', name: 'Psa Finance Argentina Compañía Financier' },
  { code: '44099', name: 'Toyota Compañía Financiera De Argentina' },
  { code: '45030', name: 'Naranja Digital Compañía Financiera S.A.' },
  { code: '45056', name: 'Montemar Compañia Financiera S.A.' },
  { code: '45072', name: 'Reba Compañia Financiera S.A.' },
  { code: '65203', name: 'Credito Regional Compañia Financiera S.A' },
];
