import { Column } from "exceljs"

// Ver, todavía no usado
export const compEmitidosHeader: Partial<Column>[] = [
  { header: 'Fecha Emisión', key: 'fecha', width: 10, },
  { header: 'Cpbte', key: 'comprobante', width: 10, },
  { header: 'Suc.', key: 'sucursal', width: 10, },
  { header: 'Número ', key: 'numeroDesde', width: 10, },
  { header: 'N° Hasta', key: 'numeroHasta', width: 10, },
  { header: 'Cód. Autorización', key: '', width: 10, },
  { header: 'Tipo Doc. ', key: '', width: 10, },
  { header: 'CUIT', key: '', width: 10, },
  { header: 'Razón Social/Denominación Comprador', key: '', width: 10, },
  { header: 'Tipo Cbio.', key: '', width: 10, },
  { header: 'Moneda', key: '', width: 10, },
  { header: 'Neto Gravado', key: '', width: 10, },
  { header: 'Importes No Gravados', key: '', width: 10, },
  { header: 'Importes Exentos', key: '', width: 10, },
  { header: 'Otros Tributos', key: '', width: 10, },
  { header: 'IVA  Crédito', key: '', width: 10, },
  { header: 'Importe   Total', key: '', width: 10, },
  { header: 'Neto Gravado', key: '', width: 10, },
  { header: 'Importes No Gravados', key: '', width: 10, },
  { header: 'Importes Exentos', key: '', width: 10, },
  { header: 'IVA  Liquidado', key: '', width: 10, },
  { header: 'Importe   Total', key: '', width: 10, },
  { header: 'Pcia', key: '', width: 10, },
  { header: 'Neto Cód. ', key: '', width: 10, },
  { header: 'Alíc.', key: '', width: 10, },
  { header: 'Neto a importar', key: '', width: 10, },
  { header: 'IVA   Débito', key: '', width: 10, },
  { header: 'NG/EX  Cód.', key: '', width: 10, },
  { header: 'P/R Cód. ', key: '', width: 10, },
  { header: 'Perc./Ret.', key: '', width: 10, },
  { header: 'Pcia P/R', key: '', width: 10, },
  { header: 'Cód Cte', key: '', width: 10, },
  { header: 'Moneda', key: '', width: 10, },
  { header: 'Pto. Vta', key: '', width: 10, },
  { header: 'Cd Dc', key: '', width: 10, },
  { header: 'DIFERENCIA', key: '', width: 10, },
]

export const comprobantesEmitidosAfip = [
  { header:'Fecha', key: 'fecha', width: 10},
  { header:'Tipo', key: 'tipo', width: 15},
  { header:'Punto de Venta', key: 'puntoVenta', width: 10},
  { header:'Número Desde', key: 'numeroDesde', width: 10},
  { header:'Número Hasta', key: 'numeroHasta', width: 10},
  { header:'Cód. Autorización', key: 'codAutorizacion', width: 10},
  { header:'Tipo Doc. Receptor', key: 'docReceptor', width: 10},
  { header:'Nro. Doc. Receptor', key: 'numeroDocReceptor', width: 15},
  { header:'Denominación Receptor', key: 'denominacion', width: 15},
  { header:'Tipo Cambio', key: 'tipoCambio', width: 10},
  { header:'Moneda', key: 'moneda', width: 10},
  { header:'Imp. Neto Gravado', key: 'gravado', width: 10},
  { header:'Imp. Neto No Gravado', key: 'noGravado', width: 10},
  { header:'Imp. Op. Exentas', key: 'exento', width: 10},
  { header:'Otros Tributos', key: 'others', width: 10},
  { header:'IVA', key: 'iva', width: 10},
  { header:'Imp. Total', key: 'total', width: 10},
];

export const comprobantesBalducchi: any = {
  FTA: '1 - Factura A',
  NDA: '2 - Nota de Débito A',
  NCA: '3 - Nota de Crédito A',
  FTB: '6 - Factura B',
  NDB: '7 - Nota de Débito B',
  NCB: '8 - Nota de Crédito B',
}